spring.application.name=guesthouse-booking-service

server.port=${PORT:8081}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${DB.URL:jdbc:mysql://booking-db:3306/bookingdb}
spring.datasource.username=${DB.USERNAME:root}
spring.datasource.password=root${DB.PASSWORD:}

customer-service.base-url=${CUSTOMER_SERVICE_URL:http://customer-service:8080/api/customers%7D

spring.jpa.hibernate.ddl-auto=update

logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error

